BEGIN;

CREATE TABLE IF NOT EXISTS news_clusters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    representative_article_id BIGINT NULL,
    search_keyword VARCHAR(255) NOT NULL,
    cluster_title TEXT,
    cluster_summary TEXT,
    normalized_title TEXT,
    normalized_description TEXT,
    title_hash CHAR(64),
    content_hash CHAR(64),
    main_keywords JSONB NULL,
    parties JSONB NULL,
    regions JSONB NULL,
    people JSONB NULL,
    first_published_at TIMESTAMPTZ,
    last_published_at TIMESTAMPTZ,
    article_count BIGINT NOT NULL DEFAULT 0,
    duplicate_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_source VARCHAR(100) NOT NULL,
    search_keyword VARCHAR(255) NOT NULL,
    title_raw TEXT,
    title TEXT,
    normalized_title TEXT,
    title_hash CHAR(64),
    description_raw TEXT,
    description TEXT,
    normalized_description TEXT,
    original_url TEXT,
    naver_url TEXT,
    canonical_url TEXT,
    canonical_url_hash CHAR(64),
    external_article_id VARCHAR(255) NOT NULL,
    source_name VARCHAR(255),
    published_at TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ,
    raw_payload JSONB,
    summary TEXT,
    main_keywords JSONB NULL,
    parties JSONB NULL,
    regions JSONB NULL,
    people JSONB NULL,
    content_hash CHAR(64),
    cluster_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_articles_api_external_id UNIQUE (api_source, external_article_id),
    CONSTRAINT uq_articles_canonical_url_hash UNIQUE (canonical_url_hash),
    CONSTRAINT fk_articles_cluster
        FOREIGN KEY (cluster_id) REFERENCES news_clusters(id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS news_api_fetch_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_source VARCHAR(100) NOT NULL,
    search_keyword VARCHAR(255) NOT NULL,
    last_build_date TIMESTAMPTZ,
    total BIGINT,
    start INTEGER,
    display INTEGER,
    fetched_count INTEGER NOT NULL DEFAULT 0,
    inserted_count INTEGER NOT NULL DEFAULT 0,
    duplicate_count INTEGER NOT NULL DEFAULT 0,
    fetched_at TIMESTAMPTZ,
    raw_response JSONB
);

CREATE TABLE IF NOT EXISTS news_crawl_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_source VARCHAR(100) NOT NULL,
    search_keyword VARCHAR(255) NOT NULL,
    last_seen_external_article_id VARCHAR(255),
    last_seen_published_at TIMESTAMPTZ,
    last_seen_title TEXT,
    last_seen_url TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_news_crawl_state_source_keyword UNIQUE (api_source, search_keyword)
);

CREATE TABLE IF NOT EXISTS news_duplicate_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cluster_id BIGINT NOT NULL,
    representative_article_id BIGINT NULL,
    api_source VARCHAR(100) NOT NULL,
    search_keyword VARCHAR(255) NOT NULL,
    duplicate_external_article_id VARCHAR(255),
    duplicate_title TEXT,
    duplicate_url TEXT,
    duplicate_published_at TIMESTAMPTZ,
    similarity_score NUMERIC(6, 4),
    duplicate_reason VARCHAR(100),
    raw_payload JSONB,
    detected_at TIMESTAMPTZ,
    CONSTRAINT fk_news_duplicate_logs_cluster
        FOREIGN KEY (cluster_id) REFERENCES news_clusters(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_news_duplicate_logs_representative_article
        FOREIGN KEY (representative_article_id) REFERENCES articles(id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_news_clusters_representative_article_id
    ON news_clusters (representative_article_id);

CREATE INDEX IF NOT EXISTS idx_news_clusters_title_hash
    ON news_clusters (title_hash);

CREATE INDEX IF NOT EXISTS idx_news_clusters_content_hash
    ON news_clusters (content_hash);

CREATE INDEX IF NOT EXISTS idx_news_clusters_first_published_at
    ON news_clusters (first_published_at);

CREATE INDEX IF NOT EXISTS idx_news_clusters_last_published_at
    ON news_clusters (last_published_at);

CREATE INDEX IF NOT EXISTS idx_news_clusters_keyword_last_published_at
    ON news_clusters (search_keyword, last_published_at);

CREATE INDEX IF NOT EXISTS idx_articles_title_hash
    ON articles (title_hash);

CREATE INDEX IF NOT EXISTS idx_articles_content_hash
    ON articles (content_hash);

CREATE INDEX IF NOT EXISTS idx_articles_published_at
    ON articles (published_at);

CREATE INDEX IF NOT EXISTS idx_articles_cluster_id
    ON articles (cluster_id);

CREATE INDEX IF NOT EXISTS idx_articles_keyword_published_at
    ON articles (search_keyword, published_at);

CREATE INDEX IF NOT EXISTS idx_news_duplicate_logs_cluster_id
    ON news_duplicate_logs (cluster_id);

CREATE INDEX IF NOT EXISTS idx_news_duplicate_logs_external_id
    ON news_duplicate_logs (api_source, duplicate_external_article_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'trg_articles_set_updated_at'
    ) THEN
        CREATE TRIGGER trg_articles_set_updated_at
        BEFORE UPDATE ON articles
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'trg_news_clusters_set_updated_at'
    ) THEN
        CREATE TRIGGER trg_news_clusters_set_updated_at
        BEFORE UPDATE ON news_clusters
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'trg_news_crawl_state_set_updated_at'
    ) THEN
        CREATE TRIGGER trg_news_crawl_state_set_updated_at
        BEFORE UPDATE ON news_crawl_state
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
    END IF;
END;
$$;

COMMIT;